// ─────────────────────────────────────────────────────────────────
//  SKILLS
//  Columns: category | sub_group (optional) | skill
// ─────────────────────────────────────────────────────────────────
// tagline appears once per category (set it on any one row in that category)
const SKILLS = [
  { category: 'Research',  tagline: 'understanding a problem space', sub_group: 'Data collection', skill: 'Semi-structured interviews'      },
  { category: 'Research',  tagline: '',                             sub_group: 'Data collection',  skill: 'Think-aloud protocols'            },
  { category: 'Research',  tagline: 'understanding a problem space', sub_group: 'Data collection', skill: 'In-the-wild sampling'      },
    { category: 'Research',  tagline: '',                             sub_group: 'Contextual inquiry', skill: 'Interaction logs'               },
  { category: 'Research',  tagline: '',                             sub_group: 'Contextual inquiry', skill: 'Observational coding'           },
  { category: 'Research',  tagline: '',                             sub_group: 'Contextual inquiry', skill: 'Video/screen analysis'          },
  { category: 'Research',  tagline: '',                             sub_group: 'Synthesis',       skill: 'Thematic analysis'               },
  { category: 'Research',  tagline: '',                             sub_group: 'Synthesis',       skill: 'Affinity diagramming'            },
  { category: 'Research',  tagline: '',                             sub_group: 'Synthesis',       skill: 'Literature review'               },
  { category: 'Design',         tagline: 'shaping interactions & visuals',           sub_group: 'Interaction design',   skill: 'Wireframing'                                     },
  { category: 'Design',         tagline: '',                                          sub_group: 'Interaction design',   skill: 'Prototyping'                                     },
  { category: 'Design',         tagline: '',                                          sub_group: 'Interaction design',   skill: 'Storyboarding'                                   },
  { category: 'Design',         tagline: '',                                          sub_group: 'Visualization design', skill: 'Visual encoding'                                 },
  { category: 'Design',         tagline: '',                                          sub_group: 'Visualization design', skill: 'Dashboard/interface layout'                      },
  { category: 'Design',         tagline: '',                                          sub_group: 'Visualization design', skill: 'Narrative'                                       },
  { category: 'Design',         tagline: '',                                          sub_group: 'Visualization design', skill: 'Legend and onboarding'                           },
  { category: 'Analyze & Build', tagline: 'making sense of data and building systems', sub_group: 'Interface prototype', skill: 'JS'                                              },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Interface prototype',  skill: 'D3.js'                                           },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Interface prototype',  skill: 'Observable'                                      },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Data analysis',        skill: 'Python (Pandas, NumPy, Matplotlib, Seaborn)'    },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Data analysis',        skill: 'SQL'                                             },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'ML',                   skill: 'OpenCV'                                          },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'ML',                   skill: 'Roboflow'                                       },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'ML',                   skill: 'CLIP'                                            },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'ML',                   skill: 'RAG'                                             },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Generative AI',        skill: 'AI image generation (for data viz)'              },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Generative AI',        skill: 'Python scripting'                                 },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Programming languages', skill: 'C#'                                            },
  { category: 'Analyze & Build', tagline: '',                                         sub_group: 'Programming languages', skill: 'Java'                                          },
  { category: 'Evaluate',  tagline: 'assessing how well a design works', sub_group: 'Qualitative evaluation', skill: 'Post-task interviews'                                      },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Qualitative evaluation', skill: 'Session observation'                                        },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Rigorous user studies', skill: 'Controlled experiments (between/within subjects)'           },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Rigorous user studies', skill: 'Usability testing'                                          },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Rigorous user studies', skill: 'Wizard of Oz'                                               },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Measurement',           skill: 'Task performance metrics (error, task completion time)'    },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Measurement',           skill: 'Standardized scales (SUS, Likert, ASQ)'                    },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Behavioral analysis',   skill: 'Interaction log analysis'                                   },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Behavioral analysis',   skill: 'Eye tracking'                                               },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'Behavioral analysis',   skill: 'A/B testing'                                                },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'AI-specific',           skill: 'Trust measurement'                                          },
  { category: 'Evaluate',  tagline: '',                                  sub_group: 'AI-specific',           skill: 'Decision making'                                            },
];

// ─────────────────────────────────────────────────────────────────
//  PROJECTS
//  Columns: name | category | description | status | meta | skills | highlight_skills | img_color
//  skills: comma-separated skill categories (must match SKILLS categories above)
//  meta: location / org / year shown on the card (edit freely)
//  highlight_skills: exact skill names from SKILLS to bold on hover (edit freely)
// ─────────────────────────────────────────────────────────────────
const PROJECTS = [
  {
    name:        'Make AI Understand Spatial Thinking',
    category:    'Human AI Interaction',
    description: 'Humans structure ideas in creative, unpredictable ways on boards. AI handles OCR and simple layouts but misses richer spatial meanings. This project teaches AI to read organization patterns from in-the-wild samples, unlocking truer digitization of physical ideation.',
    status:      'In progress',
    meta:        'SFU, 2024–2026',
    skills:      'Research, Analyze & Build',
    highlight_skills: [
      'In-the-wild sampling',
      'Thematic analysis',
      'Affinity diagramming',
      'Literature review',
      'OpenCV',
      'Roboflow',
      'CLIP',
    ],
    img_color:   '#c8d4e0',
  },
  {
    name:        'Uncertainty in AI Generated Output',
    category:    'Human AI Interaction',
    description: 'AI-generated outputs carry uncertainty and that affects how people decide. This project explores how to surface uncertainty in ways that genuinely inform hard, multi-factor decisions. I led this project, from finding an underexplored angle, to designing, building, and evaluating the uncetainty communication interface.',
    status:      'In progress',
    meta:        'Autodesk, 2025',
    skills:      'Research, Design, Analyze & Build, Evaluate',
    highlight_skills: [
      'Literature review',
      'Prototyping',
      'Visual encoding',
      'Dashboard/interface layout',
      'Narrative',
      'Legend and onboarding',
      'JS',
      'D3.js',
      'SQL',
      'Post-task interviews',
      'Session observation',
      'Usability testing',
      'Standardized scales (SUS, Likert, ASQ)',
      'Trust measurement',
      'Decision making',
    ],
    img_color:   '#d4c8e0',
  },
  {
    name:        'AI-Illusterated Memorial Data Visualization',
    category:    'Human AI Interaction',
    description: 'Built an interactive visualization of WorkSafeBC fatality data where AI illustrations were generated directly from worker death stories, with computer vision–detected figures serving as clickable data points linked to individual records.',
    status:      'In progress',
    meta:        '2026',
    skills:      'Design, Analyze & Build',
    highlight_skills: [
      'Visual encoding',
      'Dashboard/interface layout',
      'Narrative',
      'JS',
      'AI image generation (for data viz)',
      'Python scripting',
    ],
    img_color:   '#e0d8c8',
  },
  {
    name:        'Serendipitous Explanation',
    category:    'Designing for Complex Interfaces',
    description: 'People rarely read legends or onboarding text; they dive straight into interacting. This project leverages that behavior to deliver explanations serendipitously, meeting users where they already are and supporting non-linear, discovery-driven learning.',
    status:      'Done',
    meta:        'PhD thesis, SFU, 2022–2026',
    skills:      'Research, Design, Analyze & Build, Evaluate',
    highlight_skills: [
      'Semi-structured interviews',
      'Think-aloud protocols',
      'In-the-wild sampling',
      'Observational coding',
      'Video/screen analysis',
      'Literature review',
      'Thematic analysis',
      'Wireframing',
      'Prototyping',
      'Storyboarding',
      'Visual encoding',
      'Dashboard/interface layout',
      'Narrative',
      'Legend and onboarding',
      'JS',
      'D3.js',
      'SQL',
      'Controlled experiments (between/within subjects)',
      'Task performance metrics (error, task completion time)',
      'Standardized scales (SUS, Likert, ASQ)',
      'Interaction log analysis',
      'Eye tracking',
      'A/B testing',
    ],
    img_color:   '#c8e0d4',
  },

  {
    name:        '3D User Interfaces for Smart Environments',
    category:    'Designing for Complex Interfaces',
    description: 'Built and evaluated 3D user interfaces for a smart game and a smart conference application at an early-stage startup. Used a quantitative approach to analyze how interface design decisions and room complexity affected user performance in smart environments.',
    status:      'Done',
    meta:        'iSimorgh, IoT startup, 2017–2019',
    skills:      'Research, Design, Analyze & Build, Evaluate',
    highlight_skills: [
      'Literature review',
      'Prototyping',
      'JS',
      'C#',
      'Java',
      'Controlled experiments (between/within subjects)',
      'Usability testing',
      'Wizard of Oz',
      'Task performance metrics (error, task completion time)',
      'Standardized scales (SUS, Likert, ASQ)',
    ],
    img_color:   '#e0c8d0',
  },
];
